### ISSUE TITLE
Update pug-loader

### ISSUE THREAD

**Issue by webdiscus** [twgd/pug-sass-webpack#1]
Hello @twgd,

please update the `pug-loader` to release version `1.6.0` in your `package.json`:
```
 "@webdiscus/pug-loader": "^1.6.0"
```
The alpha version is deleted.

## Proposal
Instead of usage `new HtmlWebpackPlugin` for each pug template, you can try the [`pug-plugin`](https://github.com/webdiscus/pug-plugin)

For example,  Instead of this:
```js
    plugins: [
      new HtmlWebpackPlugin({
        template: './index.pug',
      }),
    ],
```
you can define the pug template in entry:
```js
const PugPlugin = require('pug-plugin');

module.exports = {
  entry: {
    script: './src/index.js',
    index: './src/index.pug', // ==> dist/index.html
    // ...
    'some-other-page':  './src/some-other-page.pug', // ==> dist/some-other-page.html
  },
  plugins: [
    new PugPlugin(),
  ],
  module: {
    rules: [
      {
        test: /\.pug$/,
        loader: PugPlugin.loader, // the pug-loader is already the part of pug-plugin
      },
    ],
  },
}
```
The `pug-plugin` supports extract CSS from `scss` directly in pug, for example:
```pug
link(rel='stylesheet' href=require('~Styles/main.scss'))
```
output
```html
<link rel="stylesheet" href="/assets/css/main.6f4d012e.css">
```
The complete working example you can [see here](https://github.com/webdiscus/pug-plugin#extract-css-via-require-in-pug).

**Comment by twgd** [comment]
Hi @webdiscus , 
I have updated the `pug-loader`.
Thank you for letting me know.
